spring.application.name=Spring Boot

spring.datasource.url=jdbc:postgresql://localhost:5432/idol
spring.datasource.username=postgres
spring.datasource.password=example

spring.jpa.hibernate.ddl-auto=update
# affiche les requêtes SQL dans les logs
spring.jpa.show-sql=true